name: Run MemorySanitizer

on:
  push:

jobs:
  run-msan:
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2 

      - name: Install MemorySanitizer dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y clang-14 libclang-14-dev llvm-14 llvm-14-dev llvm-14-tools llvm-14-linker-tools
      
      - name: Run Google Memory Sanitizer (source code) (Linux)
        if: runner.os == 'Linux'
        run: |
          set +e 
          clang -I -fsanitize=memory -fPIE -pie -O2 -fno-omit-frame-pointer -fsanitize-memory-track-origins -g thread.cc -o ./compiled.out
          ./compiled.out
